# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlistitem',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
